modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="multicraft"
version="0.3.0"
displayName="Multicraft"
logoFile="logo.png"
credits="Multicraft mod is made by Multiteam, specially by: Rellit [MAIN CODE], MaroonShaded [CODE] King_of_Creepers [TEXTURES/MODELS], and IAmGama [TEXTURES]" #optional
authors="Rellit, MaroonShaded, King_of_Creepers, and IAmGama"
description='''This mod adds the things we've been missing from minecraft for a long time, and even some new exciting features!'''
[[dependencies.multicraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.multicraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
