modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="multiexpansion"
version="${file.jarVersion}"
displayName="MultiExpansion"
logoFile="logo.png"
credits="A mod made by MultiTeam!"
authors="LazTheArtist [Code - Art]"
description='''
This is the latest iteration of the mod, but this time it will be made properly.

'''
[[dependencies.multiexpansion]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.multiexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.claysoldiers2]]
    modId="multicore_lib"
    mandatory=true
    versionRange="[1.18-0.2.2.1,)"
    ordering="AFTER"
    side="BOTH"
